name = "ProteinBenchmarkTools"
uuid = "c88d15bf-97e9-4e47-a023-49db67277a02"
authors = ["aronStalmarck <aron.stalmarck@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Foldseek_jll = "f5adda9a-30aa-5201-a847-bcd4e31b8420"
ProteinChains = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"
ProteinRefolding = "bf3ea083-9801-4107-aa43-922d748a66a0"
USalign_jll = "927da072-87df-5aff-817c-c070e1bdca98"

[compat]
Foldseek_jll = "8.0.0"
ProteinChains = "0.7.3"
ProteinRefolding = "1.0.0"
USalign_jll = "2022.9.24"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
